workflows:
  flutter_python_build:
    name: Build & Run Flutter + Python
    max_build_duration: 120
    instance_type: linux  # ✅ Linux पर चलेगा
    environment:
      flutter: stable
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.example.myapp"
    scripts:
      - name: Install Dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
      - name: Check Python Version
        script: |
          python3 --version
      - name: Install Flutter Dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install Python Dependencies
        script: |
          if [ -f "requirements.txt" ]; then pip3 install -r requirements.txt; else echo "No requirements.txt found"; fi
      - name: Run Python Script
        script: |
          chmod +x * && python3 d.py
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
