workflows:
  docker_build_and_run:
    name: Build & Run Docker
    max_build_duration: 120
    instance_type: linux  # ✅ Codemagic के सही Linux instance पर चलेगा
    environment:
      flutter: stable
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.example.myapp"
    scripts:
      - name: Install Docker (Linux)
        script: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
      - name: Check Docker Version
        script: |
          docker --version
      - name: Build Docker Image
        script: |
          docker build --no-cache -t my_docker_app .
      - name: Run Docker Container
        script: |
          docker run --rm my_docker_app
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
