workflows:
  docker_build_and_run:  # ✅ अब ये वर्कफ़्लो Codemagic में मैच करेगा!
    name: Run Python Script
    max_build_duration: 30
    instance_type: linux
    environment:
      vars:
        PYTHON_VERSION: "3.9"
    scripts:
      - name: Install Dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
      - name: Install Python Requirements
        script: |
          if [ -f "requirements.txt" ]; then pip3 install -r requirements.txt; else echo "No requirements.txt found"; fi
      - name: Set Executable Permissions
        script: |
          chmod +x *
      - name: Run Python Script
        script: |
          python3 d.py
